version: '3'
services:
  postgres:
    container_name: chat-db
    image: postgres:10-alpine
    environment:
      - 'POSTGRES_DB=chat'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=1234'
    ports:
      - '5432:5432'

